# -*- coding: utf-8 -*-
"""01_vessel_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHQW7CH95Ga5TjRdiB05yRB3gTGBJR6H
"""

!pip install -q pycocotools opencv-python albumentations matplotlib segmentation-models-pytorch timm

import os
import gc
import json
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import Dataset, DataLoader
from pycocotools.coco import COCO
from tqdm import tqdm

import albumentations as A
from albumentations.pytorch import ToTensorV2

import segmentation_models_pytorch as smp

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

import os
import shutil
from google.colab import drive

drive.mount('/content/drive')

PROJECT_ROOT = "/content/drive/MyDrive/angio_ai_project"

DATA_ROOT = os.path.join(PROJECT_ROOT, "data", "dataset_phase_1")
MODELS_ROOT = os.path.join(PROJECT_ROOT, "models", "vessel")

os.makedirs(MODELS_ROOT, exist_ok=True)

train_images = os.path.join(DATA_ROOT, "segmentation_dataset", "seg_train", "images")
train_json   = os.path.join(DATA_ROOT, "segmentation_dataset", "seg_train", "annotations", "seg_train.json")

val_images = os.path.join(DATA_ROOT, "segmentation_dataset", "seg_val", "images")
val_json   = os.path.join(DATA_ROOT, "segmentation_dataset", "seg_val", "annotations", "seg_val.json")

print(train_images)
print(train_json)
print(val_images)
print(val_json)

train_transform = A.Compose([
    A.Resize(512, 512),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=15, p=0.5),
    A.RandomBrightnessContrast(p=0.3),
    A.GaussianBlur(blur_limit=(3, 5), p=0.2),
    A.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(512, 512),
    A.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

class VesselSegmentationDataset(Dataset):
    def __init__(self, images_dir, annotation_file, transform=None):
        self.images_dir = images_dir
        self.annotation_file = annotation_file
        self.transform = transform

        self.coco = COCO(annotation_file)
        self.image_ids = list(self.coco.imgs.keys())

        self.stenosis_cat_id = 26  # نستبعد stenosis من موديل الشريان

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        image_id = self.image_ids[idx]
        image_info = self.coco.loadImgs(image_id)[0]
        image_path = os.path.join(self.images_dir, image_info["file_name"])

        image = cv2.imread(image_path)
        if image is None:
            raise FileNotFoundError(f"Image not found: {image_path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        h, w = image.shape[:2]
        mask = np.zeros((h, w), dtype=np.uint8)

        ann_ids = self.coco.getAnnIds(imgIds=image_id)
        anns = self.coco.loadAnns(ann_ids)

        for ann in anns:
            cat_id = ann["category_id"]

            # نستبعد stenosis
            if cat_id == self.stenosis_cat_id:
                continue

            ann_mask = self.coco.annToMask(ann)
            mask = np.maximum(mask, ann_mask.astype(np.uint8))

        if self.transform is not None:
            augmented = self.transform(image=image, mask=mask)
            image = augmented["image"]
            mask = augmented["mask"].float().unsqueeze(0)
        else:
            image = image.astype(np.float32) / 255.0
            image = torch.tensor(image).permute(2, 0, 1).float()
            mask = torch.tensor(mask).unsqueeze(0).float()

        return image, mask

train_dataset = VesselSegmentationDataset(
    images_dir=train_images,
    annotation_file=train_json,
    transform=train_transform
)

val_dataset = VesselSegmentationDataset(
    images_dir=val_images,
    annotation_file=val_json,
    transform=val_transform
)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

image, mask = train_dataset[0]

image_np = image.permute(1, 2, 0).numpy()
image_np = image_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
image_np = np.clip(image_np, 0, 1)

mask_np = mask.squeeze(0).numpy()

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image_np)
plt.title("Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(mask_np, cmap="gray")
plt.title("Vessel Mask")
plt.axis("off")

plt.show()

BATCH_SIZE = 2

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Train batches:", len(train_loader))
print("Val batches:", len(val_loader))

model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
    activation=None
).to(device)

print(type(model))

bce_logits = nn.BCEWithLogitsLoss()

def dice_loss_from_logits(logits, target, smooth=1e-6):
    pred = torch.sigmoid(logits)

    pred = pred.contiguous().view(-1)
    target = target.contiguous().view(-1)

    intersection = (pred * target).sum()
    dice = (2.0 * intersection + smooth) / (pred.sum() + target.sum() + smooth)
    return 1 - dice

def combined_loss(logits, target):
    bce = bce_logits(logits, target)
    dice = dice_loss_from_logits(logits, target)
    return 0.5 * bce + 0.5 * dice

def dice_score(logits, target, threshold=0.5, smooth=1e-6):
    pred = torch.sigmoid(logits)
    pred = (pred > threshold).float()

    pred = pred.contiguous().view(-1)
    target = target.contiguous().view(-1)

    intersection = (pred * target).sum()
    score = (2.0 * intersection + smooth) / (pred.sum() + target.sum() + smooth)
    return score.item()

optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="max",
    factor=0.5,
    patience=2
)

images, masks = next(iter(train_loader))
images = images.to(device)

with torch.no_grad():
    outputs = model(images)

print(outputs.shape)

gc.collect()
torch.cuda.empty_cache()
print("GPU cache cleared")

BEST_MODEL_PATH = os.path.join(MODELS_ROOT, "best_vessel_model_run2.pth")
CHECKPOINT_PATH = os.path.join(MODELS_ROOT, "vessel_checkpoint_run2.pth")
HISTORY_PATH = os.path.join(MODELS_ROOT, "vessel_history_run2.json")

EPOCHS = 20
best_val_dice = 0.0
patience = 4
patience_counter = 0

history = {
    "train_loss": [],
    "val_loss": [],
    "val_dice": []
}

scaler = torch.amp.GradScaler("cuda")

for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0

    train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS} - Train")
    for images, masks in train_bar:
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast("cuda"):
            outputs = model(images)
            loss = combined_loss(outputs, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item()
        train_bar.set_postfix(loss=loss.item())

    avg_train_loss = train_loss / len(train_loader)

    model.eval()
    val_loss = 0.0
    val_dice_total = 0.0

    with torch.no_grad():
        val_bar = tqdm(val_loader, desc=f"Epoch {epoch+1}/{EPOCHS} - Val")
        for images, masks in val_bar:
            images = images.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)

            with torch.amp.autocast("cuda"):
                outputs = model(images)
                loss = combined_loss(outputs, masks)

            val_loss += loss.item()
            batch_dice = dice_score(outputs, masks)
            val_dice_total += batch_dice

            val_bar.set_postfix(loss=loss.item(), dice=batch_dice)

    avg_val_loss = val_loss / len(val_loader)
    avg_val_dice = val_dice_total / len(val_loader)

    history["train_loss"].append(avg_train_loss)
    history["val_loss"].append(avg_val_loss)
    history["val_dice"].append(avg_val_dice)

    scheduler.step(avg_val_dice)

    print(f"\nEpoch [{epoch+1}/{EPOCHS}]")
    print(f"Train Loss: {avg_train_loss:.4f}")
    print(f"Val Loss:   {avg_val_loss:.4f}")
    print(f"Val Dice:   {avg_val_dice:.4f}")
    print(f"LR:         {optimizer.param_groups[0]['lr']:.6f}")

    if avg_val_dice > best_val_dice:
        best_val_dice = avg_val_dice
        patience_counter = 0

        torch.save(model.state_dict(), BEST_MODEL_PATH)

        with open(HISTORY_PATH, "w") as f:
            json.dump(history, f)

        torch.save({
            "epoch": epoch + 1,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "best_val_dice": best_val_dice,
            "history": history
        }, CHECKPOINT_PATH)

        print(" Best model saved.")
    else:
        patience_counter += 1
        print(f"No improvement. Patience: {patience_counter}/{patience}")

    if patience_counter >= patience:
        print(" Early stopping triggered.")
        break

print("Best Val Dice:", best_val_dice)
print("Best model path:", BEST_MODEL_PATH)

epochs_range = range(1, len(history["train_loss"]) + 1)

plt.figure(figsize=(15, 4))

plt.subplot(1, 3, 1)
plt.plot(epochs_range, history["train_loss"])
plt.title("Train Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.subplot(1, 3, 2)
plt.plot(epochs_range, history["val_loss"])
plt.title("Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.subplot(1, 3, 3)
plt.plot(epochs_range, history["val_dice"])
plt.title("Val Dice")
plt.xlabel("Epoch")
plt.ylabel("Dice")

plt.tight_layout()
plt.show()

model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=device))
model.eval()
print("Best vessel model loaded.")

indices = random.sample(range(len(val_dataset)), 5)

plt.figure(figsize=(15, 20))

for i, idx in enumerate(indices):
    image, true_mask = val_dataset[idx]

    with torch.no_grad():
        input_tensor = image.unsqueeze(0).to(device)
        pred_logits = model(input_tensor)
        pred_mask = torch.sigmoid(pred_logits)
        pred_mask = (pred_mask > 0.5).float().cpu().squeeze().numpy()

    image_np = image.permute(1, 2, 0).cpu().numpy()
    image_np = image_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
    image_np = np.clip(image_np, 0, 1)

    true_mask_np = true_mask.squeeze(0).cpu().numpy()

    plt.subplot(5, 3, i * 3 + 1)
    plt.imshow(image_np)
    plt.title(f"Image {idx}")
    plt.axis("off")

    plt.subplot(5, 3, i * 3 + 2)
    plt.imshow(true_mask_np, cmap="gray")
    plt.title("Ground Truth")
    plt.axis("off")

    plt.subplot(5, 3, i * 3 + 3)
    plt.imshow(pred_mask, cmap="gray")
    plt.title("Prediction")
    plt.axis("off")

plt.tight_layout()
plt.show()

image_path = "/content/109.png"

image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (512, 512))

orig = image.copy()

image = image.astype(np.float32) / 255.0
image = (image - np.array([0.485, 0.456, 0.406])) / np.array([0.229, 0.224, 0.225])
image = np.transpose(image, (2, 0, 1))
image = torch.tensor(image).float().unsqueeze(0).to(device)

with torch.no_grad():
    pred_logits = model(image)
    pred_mask = torch.sigmoid(pred_logits)
    pred_mask = pred_mask.cpu().numpy()[0, 0]

pred_mask_bin = (pred_mask > 0.5).astype(np.uint8)

plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(orig)
plt.title("Input Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(pred_mask_bin, cmap="gray")
plt.title("Predicted Vessel Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(orig)
plt.imshow(pred_mask_bin, alpha=0.4, cmap="jet")
plt.title("Overlay")
plt.axis("off")

plt.show()

OUTPUT_DIR = os.path.join(PROJECT_ROOT, "outputs", "overlays")
os.makedirs(OUTPUT_DIR, exist_ok=True)

overlay = orig.copy()
mask_color = np.zeros_like(overlay)
mask_color[:, :, 1] = pred_mask_bin * 255

overlay = cv2.addWeighted(overlay, 1.0, mask_color, 0.4, 0)

save_path = os.path.join(OUTPUT_DIR, "vessel_overlay_run2.png")
cv2.imwrite(save_path, cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

print("Saved to:", save_path)

print("Saved files:")
print(BEST_MODEL_PATH)
print(CHECKPOINT_PATH)
print(HISTORY_PATH)

import cv2
import numpy as np

def refine_vessel_mask(mask):
    mask = (mask > 0).astype(np.uint8) * 255

    kernel_close = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel_close)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)

    cleaned = np.zeros_like(mask)
    min_area = 60

    for i in range(1, num_labels):
        area = stats[i, cv2.CC_STAT_AREA]
        if area >= min_area:
            cleaned[labels == i] = 255

    kernel_open = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_OPEN, kernel_open)

    cleaned = (cleaned > 0).astype(np.uint8)
    return cleaned

!pip install -q scikit-image

from skimage.morphology import skeletonize

def extract_centerline(mask):
    mask_bool = mask.astype(bool)
    skeleton = skeletonize(mask_bool)
    return skeleton.astype(np.uint8)

idx = random.randint(0, len(val_dataset)-1)

image, true_mask = val_dataset[idx]

with torch.no_grad():
    input_tensor = image.unsqueeze(0).to(device)
    pred_logits = model(input_tensor)
    pred_mask = torch.sigmoid(pred_logits)
    pred_mask = (pred_mask > 0.5).float().cpu().squeeze().numpy().astype(np.uint8)

refined_mask = refine_vessel_mask(pred_mask)
centerline = extract_centerline(refined_mask)

image_np = image.permute(1, 2, 0).cpu().numpy()
image_np = image_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
image_np = np.clip(image_np, 0, 1)

true_mask_np = true_mask.squeeze(0).cpu().numpy()

plt.figure(figsize=(18, 4))

plt.subplot(1, 5, 1)
plt.imshow(image_np)
plt.title("Image")
plt.axis("off")

plt.subplot(1, 5, 2)
plt.imshow(true_mask_np, cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(1, 5, 3)
plt.imshow(pred_mask, cmap="gray")
plt.title("Prediction")
plt.axis("off")

plt.subplot(1, 5, 4)
plt.imshow(refined_mask, cmap="gray")
plt.title("Refined Mask")
plt.axis("off")

plt.subplot(1, 5, 5)
plt.imshow(centerline, cmap="gray")
plt.title("Centerline")
plt.axis("off")

plt.tight_layout()
plt.show()

OUTPUT_MASKS = os.path.join(PROJECT_ROOT, "outputs", "masks")
os.makedirs(OUTPUT_MASKS, exist_ok=True)

refined_mask_path = os.path.join(OUTPUT_MASKS, "vessel_refined_mask_run2.png")
centerline_path = os.path.join(OUTPUT_MASKS, "vessel_centerline_run2.png")

cv2.imwrite(refined_mask_path, refined_mask * 255)
cv2.imwrite(centerline_path, centerline * 255)

print("Refined mask saved to:", refined_mask_path)
print("Centerline saved to:", centerline_path)

OUTPUT_OVERLAYS = os.path.join(PROJECT_ROOT, "outputs", "overlays")
os.makedirs(OUTPUT_OVERLAYS, exist_ok=True)

overlay = (image_np * 255).astype(np.uint8).copy()
mask_color = np.zeros_like(overlay)
mask_color[:, :, 1] = refined_mask * 255

overlay_img = cv2.addWeighted(overlay, 1.0, mask_color, 0.4, 0)

overlay_path = os.path.join(OUTPUT_OVERLAYS, "vessel_refined_overlay_run2.png")
cv2.imwrite(overlay_path, cv2.cvtColor(overlay_img, cv2.COLOR_RGB2BGR))

print("Overlay saved to:", overlay_path)

model.load_state_dict(torch.load('/content/drive/MyDrive/angio_ai_project/models/vessel/best_vessel_model_run2.pth'))
model.eval()

